### ISSUE TITLE
Delete a user

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#12]
As the admin, I should be able to soft delete a user from the system. The deleted user should not be able to log in.

**Comment by Enapreev** [comment]
@jerowe we realized that we can only soft delete a user because of the existing connections between a user and other entities. Soft delete gives little value in my opinion. We can see that CLI can delete a user only if user is not associated with any assessments or interpretations so we can implement it the same way if this is what you need.

**Comment by Enapreev** [comment]
@oleg1 as discussed with @jerowe there is no need to delete a user but instead, we need to move users to "inactive" user group which should not have any gen pannels assigned. Could you please take care of it?

**Comment by oleg1** [comment]
@Enapreev ok, good. it works. Could you please specify some points about this process on frontend:
- it should be separate button or it should be triggered by click on remove user button
- should we show removed users in user list
- should we show inactive group in group list
- can admin manually set user to inactive group

**Comment by Enapreev** [comment]
@oleg1

**Comment by oleg1** [comment]
@Goodmain please use POST /user/:id/move-to-inactive/ endpoint to move user to inactive group

**Comment by Goodmain** [comment]
Done
