### ISSUE TITLE
Make the modal window wider/Remove horizontal scrollling

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#24]
Can we get rid of horizontal scrolling on New "User" modal

![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/8769958d-f3e6-4f75-b54c-9acaca775b2b) 

![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/a8075198-a709-4880-b864-23a318d5ebd0)

**Comment by Goodmain** [comment]
Fixed. Please check
