### ISSUE TITLE
Can't create a group with the same name

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#25]
STR:  
- create a group with some random name
- delete this group
- create the group with the same name again

Actual result:  
- the error appears saying "the current group was deleted"  
![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/e08da84c-69aa-4503-81f1-26d6335691da)

![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/437b8d19-e772-4f16-9fdc-117d0e137153)

Expected result:  
- I can create a group with the same name

**Comment by Enapreev** [comment]
@jerowe do you expect the same behaviour? should we fix it?

**Comment by Enapreev** [comment]
@jerowe here is the update after discussing it with the devs.  
For now, we use soft delete for this so we mostly hiding a group from a users view. We can't use hard delete for groups because we then have to break a lot of connections: groups to gen panels, groups to users and so on. For users connection, the current DB schema doesn't support a user without a group so if we go with hard delete for groups we'll have to replace the deleted groups for all users assigned to this group.

This requires changes to both ella-admin and ella-app

**Comment by jerowe** [comment]
Let's go with the soft delete. No actually deleting users. Just add them to a group called 'inactive' that does not have access to any analyses.

**Comment by Enapreev** [comment]
Ok, then this on is done.
