### ISSUE TITLE
Unable to change user's password

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#28]
If you will try to change user's password and will set a new password in the field new_password as resuld nothing changed. I mean you can't use this password for login and also we can see a raw (not encoded) password in response.

**Comment by Enapreev** [comment]
@jerowe I know we've discussed it already but I would like to clarify it once again:  
as the admin do you want to be able to set a new password for a user - so basically directly set a new pass for a user and automatically send the new pass to the user  
OR  
as the admin do you want to initiate the password reset process as it is implemented in the ella-app: send a user the link reset pass page --> where the user type in his email --> the user gets the second email with the link and token in it --> the link redirects him to set new pass page?

**Comment by jerowe** [comment]
If one is easier to implement go with that. 

Otherwise go with 2. 

> as the admin do you want to initiate the password reset process as it is implemented in the ella-app: send a user the link reset pass page --> where the user type in his email --> the user gets the second email with the link and token in it --> the link redirects him to set new pass page?

**Comment by Enapreev** [comment]
@oleg1 could you please take care of it?

**Comment by oleg1** [comment]
@Enapreev Sure. I've created related tasks:
- #42
- #43

This is not actual. I'll close.
