### ISSUE TITLE
Create Interface for viewing Finalized Analyses

### ISSUE THREAD

**Issue by jerowe** [Dabble-of-DevOps-Bio/ella-admin#38]
Use this API to get a list of finalized analyses `/api/v1/overviews/analyses/finalized/`.

![Screen Shot 2020-11-29 at 10.54.59 AM.png](https://images.zenhubusercontent.com/5396eae271d3dd016b002590/e2513e96-3531-4d4c-a7c0-fd863df42be0)

You can see the analyses here in each stage. This interface should show only the analyses under the 'Finalized' tab.

Each next to each analysis should be a button to 'Generate Clinical Report'.

**Comment by oleg1** [comment]
@Goodmain Please implement Analysis page. This page should contain only finalyzed analysis.
