### ISSUE TITLE
CRUD gene panels

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#4]
As the admin, I should be able to CRUD gene panels which relation to analysis as many-to-many

**Comment by Enapreev** [comment]
@jerowe  
- should users be able to CRUD gene panels as well? 
- should users be able to add analysis to the panels on their own?

**Comment by jerowe** [comment]
Let's put this one on hold. I want to think of a better way to create gene panels, preferably from existing data files.

**Comment by oleg1** [comment]
Use cli commands as discussed.

> For gene panels and analyses just expose the cli as REST endpoints.
> 
> Here are the commands from the command line -
> 
> ella-cli deposit analyses /path/to/file
> or
> ella-cli deposit analyses /path/to/file --ped /path/to/ped_file
> 
> ella-cli deposit genepanel --transcripts_file /path/to/transcripts --phenotype_file /path/to/phenotype_file

**Comment by Enapreev** [comment]
put this on hold per Jillian's request

**Comment by Enapreev** [comment]
closing this one as no longer actual. Assign gen panel to a user group will be implemented in another ticket
