### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by oleg1** [Dabble-of-DevOps-Bio/ella-admin#42]
Create change password page.
Page url - **/reset-password**

**Comment by oleg1** [comment]
@Enapreev FYI

**Comment by Goodmain** [comment]
Done except one thing which may be improved. Could you please provide a list of password requirements?

**Comment by Goodmain** [comment]
PASSWORD REQUIREMENTS:
3 OF THE FOLLOWING:
✗ Minimum 8 letters
✗ Uppercase letters [A-Z]
✗ Lowercase letters [a-z]
✗ Digits [0-9]
✗ Special characters
