### ISSUE TITLE
Create and Read Analisys

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#5]
As the admin, I should be able to create analysis our of the uploaded data and add analysis to a gene panel

**Comment by Enapreev** [comment]
@jerowe did I understand the task correctly?

**Comment by jerowe** [comment]
@Enapreev yes. When you create an analysis you add a file, and that file has the format `{analysis_name}.{genepanel_name}-{genepanel_version}.vcf` or `{analysis_name}.{genepanel_name}-{genepanel_version}.vcf.gz`, and optionally a different file called a ped (for pedigree) file.

You can take a look at the ella cli.

```
docker-compose -f local.yml \
  exec ella-web \
   bash -c "ella-cli deposit analysis \
/ella/src/vardb/testdata/analyses/default/brca_sample_3.HBOCUTV_v01/brca_sample_3.HBOCUTV_v01.vcf"
```

Or with the ped 

```
	docker-compose -f local.yml \
		exec ella-web \
		bash -c "ella-cli deposit analysis \
			--ped /ella/src/vardb/testdata/analyses/default/HG002-Trio.Mendeliome_v01/HG002-Trio.Mendeliome_v01.ped
			/ella/src/vardb/testdata/analyses/default/HG002-Trio.Mendeliome_v01/HG002-Trio.Mendeliome_v01.vcf"
```

This doesn't need to be in the UI, only a REST API endpoint.

**Comment by Enapreev** [comment]
put this on hold per Jillian's request
