### ISSUE TITLE
Implement Gene analize table

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#72]
![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/edced845-db27-4ae2-8418-6d3954468ed9)

**Comment by oleg1** [comment]
Done on backend.

**Comment by oleg1** [comment]
Duplicated here #64

**Comment by oleg1** [comment]
Duplicated here #64
