### ISSUE TITLE
Implemnet Header and Footer

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#74]
As the admin I should be able to replace header and footer images for a particular customer. These should be a replaceable .jpg file
It is important to know the file height and width in px 

![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/be79942b-560d-4efc-a1fe-ec27593fb186)  
![image.png](https://images.zenhubusercontent.com/5fad167bfd206ab7edd7e652/09449f8f-5ce9-43c0-913d-c0620aaf4555)

**Comment by oleg1** [comment]
@Goodmain Let's implement it on frontend side as static images. While deploy for customer devops just replace it by customer specific images.
