### ISSUE TITLE
Login page + log in to both apps

### ISSUE THREAD

**Issue by Enapreev** [Dabble-of-DevOps-Bio/ella-admin#8]
I think we can fully reuse this login page, but change Ella to Ella Admin in the header 
![image](https://user-images.githubusercontent.com/44634151/98898543-12b01e80-24d8-11eb-8275-722157e5c0d2.png)

+ implement the login to both apps: initial ella app and our ella admin

**Comment by jerowe** [comment]
When you login through the base ella package it creates a AuthToken and a session token. 

The behavior is also documented here - https://dabble-of-devops-ella-admin-docs.s3.amazonaws.com/Understanding-The-Ella-REST-API/Ella-REST-API-Overview.html

![Screen Shot 2020-11-11 at 10.14.49 AM.png](https://images.zenhubusercontent.com/5396eae271d3dd016b002590/950eb633-5b98-4b7a-9fa7-7e7027e36434)
